project_id = "ttzioshkresaqmsodhfb"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 9999
site_url = "https://hiclient.co"
additional_redirect_urls = [
  "https://ttzioshkresaqmsodhfb.supabase.co",
  "https://hiclient.co",
  "http://localhost:8080",
  "https://ttzioshkresaqmsodhfb.functions.supabase.co",
  "http://localhost:3000",
  "http://localhost:5173",
  "http://127.0.0.1:8080",
  "http://127.0.0.1:3000",
  "http://127.0.0.1:5173"
]
jwt_expiry = 3600
refresh_token_rotation_enabled = true
security_update_password_require_reauthentication = true
email_template_fetch_url = "https://hiclient.co/email-templates"
email_template_override_path = "email-templates"

[functions.paddle-webhook]
verify_jwt = false

[functions.widget-js]
verify_jwt = false

[edge-runtime]
enabled = true
port = 54322
inspector_port = 8083