
project_id = "ttzioshkresaqmsodhfb"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 9999
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://ttzioshkresaqmsodhfb.supabase.co"]
jwt_expiry = 3600
refresh_token_rotation_enabled = true
security_update_password_require_reauthentication = true

[functions.paddle-webhook]
verify_jwt = false

[functions.widget-js]
verify_jwt = false

[edge-runtime]
enabled = true
port = 54322
inspector_port = 8083
