import type { WidgetTemplate } from '../template-types.ts'

export function getMinimalistTemplate(): WidgetTemplate {
  return {
    id: 'minimalist',
    name: 'Minimalist',
    description: 'Simple icons-only design with hover tooltips',
    html: `
      <div class="minimalist-widget-container position-{{POSITION}}" id="minimalist-widget-container">
        <div class="minimalist-channels-list" id="minimalist-channels-list">
          <!-- Channels will be generated by JavaScript -->
        </div>
        <button class="minimalist-main-button" id="minimalist-main-button" style="background: {{BUTTON_COLOR}}; width: {{BUTTON_SIZE}}px; height: {{BUTTON_SIZE}}px;">
          {{BUTTON_ICON}}
        </button>
        <div class="minimalist-tooltip position-{{TOOLTIP_POSITION}} {{TOOLTIP_DISPLAY}}" id="minimalist-tooltip">
          {{TOOLTIP_TEXT}}
        </div>
      </div>
    `,
    css: `
      .minimalist-widget-container {
        position: fixed;
        z-index: 9999;
        font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', system-ui, sans-serif;
        bottom: 20px;
      }

      .minimalist-widget-container.position-right {
        right: 20px;
      }

      .minimalist-widget-container.position-left {
        left: 20px;
      }

      .minimalist-main-button {
        border-radius: 50%;
        border: none;
        cursor: pointer;
        display: flex;
        align-items: center;
        justify-content: center;
        font-size: 24px;
        color: white;
        box-shadow: 0 4px 20px rgba(0, 0, 0, 0.15);
        transition: all 0.3s cubic-bezier(0.4, 0, 0.2, 1);
        position: relative;
        z-index: 10001;
      }

      .minimalist-main-button:hover {
        transform: translateY(-2px) scale(1.05);
        box-shadow: 0 8px 30px rgba(0, 0, 0, 0.2);
      }

      .minimalist-main-button.active {
        transform: rotate(45deg);
        background: #e11d48 !important;
      }

      .minimalist-channels-list {
        position: absolute;
        bottom: calc({{BUTTON_SIZE}}px + 15px);
        display: flex;
        flex-direction: column;
        gap: 12px;
        opacity: 0;
        visibility: hidden;
        transform: translateY(20px);
        transition: all 0.4s cubic-bezier(0.4, 0, 0.2, 1);
        z-index: 10000;
        align-items: center;
      }

      .minimalist-channels-list.show {
        opacity: 1;
        visibility: visible;
        transform: translateY(0);
      }

      .minimalist-channel-btn {
        width: 60px;
        height: 60px;
        border-radius: 50%;
        border: none;
        cursor: pointer;
        display: flex;
        align-items: center;
        justify-content: center;
        font-size: 20px;
        color: white;
        text-decoration: none;
        box-shadow: 0 4px 15px rgba(0, 0, 0, 0.1);
        transition: all 0.3s cubic-bezier(0.4, 0, 0.2, 1);
        position: relative;
        transform: scale(0) translateY(20px);
        opacity: 0;
      }

      .minimalist-channels-list.show .minimalist-channel-btn {
        transform: scale(1) translateY(0);
        opacity: 1;
      }

      .minimalist-channels-list.show .minimalist-channel-btn:nth-child(1) {
        transition-delay: 0.1s;
      }

      .minimalist-channels-list.show .minimalist-channel-btn:nth-child(2) {
        transition-delay: 0.2s;
      }

      .minimalist-channels-list.show .minimalist-channel-btn:nth-child(3) {
        transition-delay: 0.3s;
      }

      .minimalist-channels-list.show .minimalist-channel-btn:nth-child(4) {
        transition-delay: 0.4s;
      }

      .minimalist-channels-list.show .minimalist-channel-btn:nth-child(5) {
        transition-delay: 0.5s;
      }

      .minimalist-channels-list.show .minimalist-channel-btn:nth-child(6) {
        transition-delay: 0.6s;
      }

      .minimalist-channel-btn:hover {
        transform: translateY(-3px) scale(1.1);
        box-shadow: 0 8px 25px rgba(0, 0, 0, 0.2);
      }

      /* Platform colors - matching the image */
      .minimalist-channel-btn[data-type="whatsapp"] { background: #4ade80; } /* Green */
      .minimalist-channel-btn[data-type="telegram"] { background: #0088cc; }
      .minimalist-channel-btn[data-type="instagram"] { background: #e4405f; } /* Pink/Red */
      .minimalist-channel-btn[data-type="messenger"] { background: #0084ff; }
      .minimalist-channel-btn[data-type="viber"] { background: #665cac; }
      .minimalist-channel-btn[data-type="skype"] { background: #00aff0; }
      .minimalist-channel-btn[data-type="discord"] { background: #5865f2; }
      .minimalist-channel-btn[data-type="tiktok"] { background: #000000; }
      .minimalist-channel-btn[data-type="youtube"] { background: #ff0000; }
      .minimalist-channel-btn[data-type="facebook"] { background: #1877f2; }
      .minimalist-channel-btn[data-type="twitter"] { background: #1da1f2; }
      .minimalist-channel-btn[data-type="linkedin"] { background: #0077b5; }
      .minimalist-channel-btn[data-type="github"] { background: #333333; }
      .minimalist-channel-btn[data-type="website"] { background: #6b7280; }
      .minimalist-channel-btn[data-type="chatbot"] { background: #8b5cf6; }
      .minimalist-channel-btn[data-type="email"] { background: #dc2626; } /* Red */
      .minimalist-channel-btn[data-type="phone"] { background: #34d399; }
      .minimalist-channel-btn[data-type="custom"] { background: #6b7280; }
      .minimalist-channel-btn.close-button { background: #e11d48; } /* Rose/Red */

      /* Channel name tooltip */
      .minimalist-channel-btn .channel-name {
        position: absolute;
        left: -10px;
        transform: translateX(-100%);
        background: rgba(0, 0, 0, 0.8);
        color: white;
        padding: 6px 10px;
        border-radius: 6px;
        font-size: 14px;
        white-space: nowrap;
        opacity: 0;
        visibility: hidden;
        transition: all 0.2s ease;
        pointer-events: none;
      }

      .minimalist-widget-container.position-left .minimalist-channel-btn .channel-name {
        left: auto;
        right: -10px;
        transform: translateX(100%);
      }

      .minimalist-channel-btn:hover .channel-name {
        opacity: 1;
        visibility: visible;
      }

      /* Tooltip */
      .minimalist-tooltip {
        position: absolute;
        background: rgba(0, 0, 0, 0.8);
        color: white;
        padding: 8px 12px;
        border-radius: 8px;
        font-size: 14px;
        white-space: nowrap;
        pointer-events: none;
        opacity: 0;
        transition: opacity 0.3s ease;
        z-index: 10003;
      }

      .minimalist-tooltip.show, .minimalist-tooltip.always {
        opacity: 1;
      }

      .minimalist-tooltip.position-top {
        bottom: calc(100% + 10px);
        left: 50%;
        transform: translateX(-50%);
      }

      .minimalist-tooltip.position-bottom {
        top: calc(100% + 10px);
        left: 50%;
        transform: translateX(-50%);
      }

      .minimalist-tooltip.position-left {
        right: calc(100% + 10px);
        top: 50%;
        transform: translateY(-50%);
      }

      .minimalist-tooltip.position-right {
        left: calc(100% + 10px);
        top: 50%;
        transform: translateY(-50%);
      }

      /* Special styles for Instagram button to match the image */
      .minimalist-channel-btn[data-type="instagram"] {
        background: #e4405f;
        border-radius: 50%;
      }

      /* Special styles for rectangular Instagram button */
      .minimalist-channel-btn.instagram-rect {
        border-radius: 12px;
        width: auto;
        padding: 0 20px;
        background: #333;
        color: white;
        font-weight: bold;
        font-size: 16px;
      }

      @media (max-width: 768px) {
        .minimalist-widget-container {
          right: 15px !important;
          left: auto !important;
          bottom: 15px !important;
        }
        
        .minimalist-channel-btn .channel-name {
          left: auto;
          right: -10px;
          transform: translateX(100%);
        }
      }
    `,
    js: `
      (function() {
        console.log('Minimalist widget JavaScript loading...');
        
        let isMenuOpen = false;
        
        function initWidget() {
          console.log("Initializing minimalist widget...");
          
          const button = document.getElementById('minimalist-main-button');
          const channelsList = document.getElementById('minimalist-channels-list');
          const tooltip = document.getElementById('minimalist-tooltip');
          const container = document.getElementById('minimalist-widget-container');
          
          if (!button || !channelsList || !container) {
            console.error('Widget elements not found:', { 
              button: !!button, 
              channelsList: !!channelsList,
              container: !!container
            });
            return;
          }

          console.log('Found widget elements:', { 
            button: !!button, 
            channelsList: !!channelsList, 
            tooltip: !!tooltip 
          });

          // Generate channels
          generateChannels();

          // Button click handler
          button.addEventListener('click', function(e) {
            e.preventDefault();
            e.stopPropagation();
            console.log("Widget button clicked, current state:", isMenuOpen);
            toggleMenu();
          });

          // Tooltip functionality
          if (tooltip) {
            const tooltipDisplay = '{{TOOLTIP_DISPLAY}}';
            
            if (tooltipDisplay === 'hover') {
              button.addEventListener('mouseenter', function() {
                if (!isMenuOpen) {
                  tooltip.classList.add('show');
                }
              });
              
              button.addEventListener('mouseleave', function() {
                tooltip.classList.remove('show');
              });
            } else if (tooltipDisplay === 'always') {
              tooltip.classList.add('always');
            }
          }

          // Close menu when clicking outside
          document.addEventListener('click', function(e) {
            if (!e.target.closest('.minimalist-widget-container')) {
              closeMenu();
            }
          });
          
          console.log('Minimalist widget initialized successfully');
        }

        function generateChannels() {
          const channelsList = document.getElementById('minimalist-channels-list');
          if (!channelsList) return;
          
          const channelsData = {{CHANNELS_DATA}};
          if (!channelsData || !channelsData.length) {
            console.log('No channels data available');
            return;
          }
          
          let html = '';
          
          // Process channels in reverse order to match the image (bottom to top)
          const reversedChannels = [...channelsData].reverse();
          
          // Add channels
          reversedChannels.forEach((channel, index) => {
            const channelUrl = getChannelUrl(channel);
            const channelIcon = getChannelIcon(channel);
            
            // Special case for Instagram to match the image
            if (channel.type === 'instagram' && index === reversedChannels.length - 1) {
              html += '<a href="' + escapeHtml(channelUrl) + '" target="_blank" ';
              html += 'class="minimalist-channel-btn instagram-rect" ';
              html += 'onclick="window.openChannel && window.openChannel(\'' + escapeHtml(channelUrl) + '\'); return false;">';
              html += 'Instagram';
              html += '</a>';
            } else {
              html += '<a href="' + escapeHtml(channelUrl) + '" target="_blank" ';
              html += 'class="minimalist-channel-btn" data-type="' + escapeHtml(channel.type) + '" ';
              html += 'onclick="window.openChannel && window.openChannel(\'' + escapeHtml(channelUrl) + '\'); return false;">';
              html += channelIcon;
              html += '<span class="channel-name">' + escapeHtml(channel.label) + '</span>';
              html += '</a>';
            }
          });
          
          // Add close button at the bottom
          html += '<button class="minimalist-channel-btn close-button" onclick="closeMinimalistMenu()">';
          html += '<svg width="24" height="24" fill="white" viewBox="0 0 24 24"><path d="M19 6.41L17.59 5 12 10.59 6.41 5 5 6.41 10.59 12 5 17.59 6.41 19 12 13.41 17.59 19 19 17.59 13.41 12z"/></svg>';
          html += '<span class="channel-name">Close</span>';
          html += '</button>';
          
          channelsList.innerHTML = html;
        }

        function getChannelUrl(channel) {
          switch (channel.type) {
            case 'whatsapp':
              return 'https://wa.me/' + channel.value.replace(/\\D/g, '');
            case 'telegram':
              return 'https://t.me/' + channel.value.replace('@', '');
            case 'email':
              return 'mailto:' + channel.value;
            case 'phone':
              return 'tel:' + channel.value;
            case 'instagram':
              return channel.value.startsWith('http') ? channel.value : 'https://instagram.com/' + channel.value.replace('@', '');
            case 'facebook':
              return channel.value.startsWith('http') ? channel.value : 'https://facebook.com/' + channel.value;
            case 'twitter':
              return channel.value.startsWith('http') ? channel.value : 'https://twitter.com/' + channel.value.replace('@', '');
            case 'linkedin':
              return channel.value.startsWith('http') ? channel.value : 'https://linkedin.com/in/' + channel.value;
            default:
              return channel.value.startsWith('http') ? channel.value : 'https://' + channel.value;
          }
        }

        function getChannelIcon(channel) {
          if (channel.customIcon) {
            return '<img src="' + channel.customIcon + '" style="width: 24px; height: 24px;" alt="' + channel.type + '">';
          }

          const icons = {
            whatsapp: '<svg width="24" height="24" fill="currentColor" viewBox="0 0 24 24"><path d="M17.6 6.32A8.78 8.78 0 0 0 12.38 4C7.59 4 3.7 7.89 3.7 12.68c0 1.56.41 3.09 1.18 4.43L3.61 22l5.02-1.32a8.74 8.74 0 0 0 3.76.86h.01c4.8 0 8.7-3.89 8.7-8.68 0-2.32-.9-4.5-2.5-6.14zm-5.22 13.32h-.01a7.25 7.25 0 0 1-3.71-1.01l-.27-.16-2.75.72.73-2.68-.17-.28a7.3 7.3 0 0 1-1.12-3.93c0-4.03 3.28-7.31 7.32-7.31a7.3 7.3 0 0 1 7.31 7.31c0 4.03-3.28 7.32-7.33 7.32zm4-5.54c-.22-.11-1.3-.64-1.5-.71s-.35-.11-.49.11c-.14.22-.56.71-.69.86-.13.14-.25.16-.47.05a5.89 5.89 0 0 1-1.73-1.07 6.5 6.5 0 0 1-1.2-1.49c-.13-.22-.01-.34.09-.45.09-.1.22-.25.33-.38.11-.13.14-.22.22-.36.07-.14.04-.25-.02-.36-.07-.11-.49-1.17-.67-1.6-.18-.42-.36-.36-.49-.37h-.42c-.14 0-.38.05-.58.27s-.76.74-.76 1.8c0 1.07.78 2.1.89 2.24.11.14 1.55 2.37 3.76 3.32.53.23.93.36 1.25.47.53.17 1 .14 1.38.08.42-.06 1.3-.53 1.48-1.04.18-.51.18-.94.13-1.04-.05-.09-.19-.14-.4-.25z"/></svg>',
            telegram: '<svg width="24" height="24" fill="currentColor" viewBox="0 0 24 24"><path d="M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2zm4.64 6.8c-.15 1.58-.8 5.42-1.13 7.19-.14.75-.42 1-.68 1.03-.58.05-1.02-.38-1.58-.75-.88-.58-1.38-.94-2.23-1.5-.99-.65-.35-1.01.22-1.59.15-.15 2.71-2.48 2.76-2.69.01-.03.01-.13-.05-.18s-.15-.03-.21-.02c-.08.02-1.49.95-4.22 2.79-.4.27-.76.41-1.08.4-.36-.01-1.04-.2-1.55-.37-.63-.2-1.12-.31-1.08-.66.02-.18.27-.36.74-.55 2.92-1.27 4.86-2.11 5.83-2.51 2.78-1.16 3.35-1.36 3.73-1.36.08 0 .27.02.39.12.1.08.13.19.14.27-.01.06.01.24 0 .38z"/></svg>',
            phone: '<svg width="24" height="24" fill="currentColor" viewBox="0 0 24 24"><path d="M6.62 10.79c1.44 2.83 3.76 5.14 6.59 6.59l2.2-2.2c.27-.27.67-.36 1.02-.24 1.12.37 2.33.57 3.57.57.55 0 1 .45 1 1V20c0 .55-.45 1-1 1-9.39 0-17-7.61-17-17 0-.55.45-1 1-1h3.5c.55 0 1 .45 1 1 0 1.25.2 2.45.57 3.57.11.35.03.74-.25 1.02l-2.2 2.2z"/></svg>',
            email: '<svg width="24" height="24" fill="currentColor" viewBox="0 0 24 24"><path d="M20 4H4c-1.1 0-1.99.9-1.99 2L2 18c0 1.1.9 2 2 2h16c1.1 0 2-.9 2-2V6c0-1.1-.9-2-2-2zm0 4l-8 5-8-5V6l8 5 8-5v2z"/></svg>',
            instagram: '<svg width="24" height="24" fill="currentColor" viewBox="0 0 24 24"><path d="M12 2.163c3.204 0 3.584.012 4.85.07 3.252.148 4.771 1.691 4.919 4.919.058 1.265.069 1.645.069 4.849 0 3.205-.012 3.584-.069 4.849-.149 3.225-1.664 4.771-4.919 4.919-1.266.058-1.644.07-4.85.07-3.204 0-3.584-.012-4.849-.07-3.26-.149-4.771-1.699-4.919-4.92-.058-1.265-.07-1.644-.07-4.849 0-3.204.013-3.583.07-4.849.149-3.227 1.664-4.771 4.919-4.919 1.266-.057 1.645-.069 4.849-.069zm0-2.163c-3.259 0-3.667.014-4.947.072-4.358.2-6.78 2.618-6.98 6.98-.059 1.281-.073 1.689-.073 4.948 0 3.259.014 3.668.072 4.948.2 4.358 2.618 6.78 6.98 6.98 1.281.058 1.689.072 4.948.072 3.259 0 3.668-.014 4.948-.072 4.354-.2 6.782-2.618 6.979-6.98.059-1.28.073-1.689.073-4.948 0-3.259-.014-3.667-.072-4.947-.196-4.354-2.617-6.78-6.979-6.98-1.281-.059-1.69-.073-4.949-.073zm0 5.838c-3.403 0-6.162 2.759-6.162 6.162s2.759 6.163 6.162 6.163 6.162-2.759 6.162-6.163c0-3.403-2.759-6.162-6.162-6.162zm0 10.162c-2.209 0-4-1.79-4-4 0-2.209 1.791-4 4-4s4 1.791 4 4c0 2.21-1.791 4-4 4zm6.406-11.845c-.796 0-1.441.645-1.441 1.44s.645 1.44 1.441 1.44c.795 0 1.439-.645 1.439-1.44s-.644-1.44-1.439-1.44z"/></svg>',
            facebook: '<svg width="24" height="24" fill="currentColor" viewBox="0 0 24 24"><path d="M24 12.073c0-6.627-5.373-12-12-12s-12 5.373-12 12c0 5.99 4.388 10.954 10.125 11.854v-8.385H7.078v-3.47h3.047V9.43c0-3.007 1.792-4.669 4.533-4.669 1.312 0 2.686.235 2.686.235v2.953H15.83c-1.491 0-1.956.925-1.956 1.874v2.25h3.328l-.532 3.47h-2.796v8.385C19.612 23.027 24 18.062 24 12.073z"/></svg>',
            chatbot: '<svg width="24" height="24" fill="currentColor" viewBox="0 0 24 24"><path d="M20 2H4c-1.1 0-2 .9-2 2v18l4-4h14c1.1 0 2-.9 2-2V4c0-1.1-.9-2-2-2zm-7 12h-2v-2h2v2zm0-4h-2V6h2v4z"/></svg>',
            custom: '<svg width="24" height="24" fill="currentColor" viewBox="0 0 24 24"><path d="M10 6H6a2 2 0 00-2 2v8a2 2 0 002 2h4v-2H6V8h4V6zM14 6v2h4v8h-4v2h4a2 2 0 002-2V8a2 2 0 00-2-2h-4zM12 11h-2v2h2v-2z"/></svg>'
          };
          
          return icons[channel.type] || icons.custom;
        }

        function escapeHtml(text) {
          if (!text) return '';
          return String(text)
            .replace(/&/g, '&amp;')
            .replace(/</g, '&lt;')
            .replace(/>/g, '&gt;')
            .replace(/"/g, '&quot;')
            .replace(/'/g, '&#039;');
        }

        function toggleMenu() {
          const button = document.getElementById('minimalist-main-button');
          const channelsList = document.getElementById('minimalist-channels-list');
          const tooltip = document.getElementById('minimalist-tooltip');
          
          if (!channelsList || !button) {
            console.error('Channels list or button not found');
            return;
          }
          
          isMenuOpen = !isMenuOpen;
          console.log('Toggling menu, new state:', isMenuOpen);
          
          if (isMenuOpen) {
            channelsList.classList.add('show');
            button.classList.add('active');
            if (tooltip) tooltip.classList.remove('show');
          } else {
            channelsList.classList.remove('show');
            button.classList.remove('active');
          }
        }

        function closeMenu() {
          const button = document.getElementById('minimalist-main-button');
          const channelsList = document.getElementById('minimalist-channels-list');
          if (channelsList && button) {
            channelsList.classList.remove('show');
            button.classList.remove('active');
            isMenuOpen = false;
          }
        }

        // Global channel opener
        window.openChannel = function(url) {
          console.log('Opening channel:', url);
          window.open(url, '_blank');
        };

        // Global close function
        window.closeMinimalistMenu = function() {
          closeMenu();
        };

        // Initialize when DOM is ready
        if (document.readyState === 'loading') {
          document.addEventListener('DOMContentLoaded', initWidget);
        } else {
          initWidget();
        }
      })();
    `
  };
}