export const defaultHtmlTemplate = `
<div id="lovable-widget-container" style="position: fixed; {{POSITION_STYLE}} bottom: 20px; z-index: 999999;">
  <!-- Tooltip -->
  <div id="lovable-widget-tooltip" style="{{TOOLTIP_POSITION_STYLE}} display: none; position: absolute; background: rgba(0, 0, 0, 0.8); color: white; padding: 8px 12px; border-radius: 6px; font-size: 14px; white-space: nowrap; z-index: 1000000; transition: all 0.2s ease; pointer-events: none;">
    {{TOOLTIP_TEXT}}
  </div>
  
  <!-- Main Button -->
  <button id="lovable-widget-button" style="width: {{BUTTON_SIZE}}px; height: {{BUTTON_SIZE}}px; border-radius: 50%; background: {{BUTTON_COLOR}}; border: none; cursor: pointer; box-shadow: 0 4px 10px rgba(0, 0, 0, 0.2); display: flex; align-items: center; justify-content: center; transition: all 0.3s ease; position: relative; z-index: 1000000;">
    {{BUTTON_ICON}}
  </button>
</div>

<!-- Modal -->
<div id="lovable-widget-modal" style="position: fixed; top: 0; left: 0; width: 100%; height: 100%; background: rgba(0, 0, 0, 0.7); z-index: 1000001; display: none; align-items: center; justify-content: center; opacity: 0; visibility: hidden; transition: opacity 0.3s ease;">
  <div id="lovable-modal-content" style="background: white; border-radius: 16px; max-width: 400px; width: 90%; max-height: 80vh; overflow-y: auto; padding: 24px; box-shadow: 0 20px 50px rgba(0, 0, 0, 0.3); transform: translateY(20px); transition: transform 0.3s ease; position: relative;">
    <!-- Close Button -->
    <button id="lovable-widget-close" style="position: absolute; top: 16px; right: 16px; background: none; border: none; font-size: 24px; line-height: 1; color: #999; cursor: pointer; padding: 0; width: 24px; height: 24px; display: flex; align-items: center; justify-content: center; transition: all 0.2s ease;">×</button>
    
    <!-- Header -->
    <div style="margin-bottom: 20px; padding-right: 20px;">
      <h3 style="margin: 0; font-size: 18px; color: #333; font-weight: 600;">{{GREETING_MESSAGE}}</h3>
    </div>
    
    <!-- Video (if enabled) -->
    {{VIDEO_CONTENT}}
    
    <!-- Channels -->
    <div id="lovable-widget-channels" style="display: flex; flex-direction: column; gap: 10px;">
      <!-- Channels will be generated by JavaScript -->
    </div>
    
    <!-- Empty State (shown if no channels) -->
    <div class="lovable-empty-state" style="display: none; text-align: center; padding: 30px 0; color: #999;">
      <div style="font-size: 32px; margin-bottom: 10px;">📞</div>
      <p style="margin: 0; font-size: 14px;">No contact channels available</p>
    </div>
  </div>
</div>
`;